# Generated by Django 4.0.6 on 2022-07-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='unregistred',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
